name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: |
          echo "${{ secrets.ENV_PROD }}" > .env.production
          pnpm run build:lib
          pnpm run build

      - name: Clone website repo
        uses: GuillaumeFalourd/clone-github-repo-action@v1
        with:
          owner: hello-nav
          repository: hello-nav.github.io
          access-token: ${{ secrets.ACCESS_TOKEN }}

      - name: Deploy
        run: |
          sudo chown -R $USER:$USER ./hello-nav.github.io
          cd hello-nav.github.io
          rm -rf ./*
          cp -r ../dist/* ./
          git config --global user.name ${{ secrets.REPO_USER }}
          git config --global user.email ${{ secrets.REPO_EMAIL }}
          git add .
          git commit -m 'CI BUILD'
          git push origin master
